name: stremio_jacket
services:
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    network_mode: "container:gluetun-mcw84kk8os0owck40kg0osgg"
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - PUID=1002
      - PGID=1002
      - TZ=America/Los_Angeles
#    networks:
#      - stremio_jacket_network
#    ports:
#      - "${PORT:-8191}:8191"
    restart: unless-stopped
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    network_mode: "container:gluetun-mcw84kk8os0owck40kg0osgg"
    environment:
      - PUID=1002
      - PGID=1002
      - TZ=America/Los_Angeles
      - AUTO_UPDATE=true #optional
      - RUN_OPTS= #optional
    depends_on:
      - flaresolverr
#    networks:
#      - stremio_jacket_network
    volumes:
      - ./data:/config
      - /path/to/blackhole:/downloads
    restart: unless-stopped
  jackett-stremio:
    image: belmeg/stremio-addon-jackett
    container_name: jackett-stremio
    environment:
      - PUID=1002
      - PGID=1002
      - TZ=America/Los_Angeles
      - ADDON_NAME=stremio_jacket
    depends_on:
      - jackett
#    networks:
#      - stremio_jacket_network
    ports:
      - 3007:3000
    restart: unless-stopped

#networks:
#    stremio_jacket_network:
#        external: true
#        name: stremio_jacket_network
